/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SfStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLSfStockPriceElement extends Components.SfStockPrice, HTMLStencilElement {
    }
    var HTMLSfStockPriceElement: {
        prototype: HTMLSfStockPriceElement;
        new (): HTMLSfStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "sf-stock-price": HTMLSfStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface SfStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "sf-stock-price": SfStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sf-stock-price": LocalJSX.SfStockPrice & JSXBase.HTMLAttributes<HTMLSfStockPriceElement>;
        }
    }
}
