/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SfSideDrawer {
        "my_title": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface SfTooltip {
        "showTip": boolean;
        "tip": string;
    }
}
declare global {
    interface HTMLSfSideDrawerElement extends Components.SfSideDrawer, HTMLStencilElement {
    }
    var HTMLSfSideDrawerElement: {
        prototype: HTMLSfSideDrawerElement;
        new (): HTMLSfSideDrawerElement;
    };
    interface HTMLSfTooltipElement extends Components.SfTooltip, HTMLStencilElement {
    }
    var HTMLSfTooltipElement: {
        prototype: HTMLSfTooltipElement;
        new (): HTMLSfTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "sf-side-drawer": HTMLSfSideDrawerElement;
        "sf-tooltip": HTMLSfTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SfSideDrawer {
        "my_title"?: string;
        "opened"?: boolean;
    }
    interface SfTooltip {
        "showTip"?: boolean;
        "tip"?: string;
    }
    interface IntrinsicElements {
        "sf-side-drawer": SfSideDrawer;
        "sf-tooltip": SfTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sf-side-drawer": LocalJSX.SfSideDrawer & JSXBase.HTMLAttributes<HTMLSfSideDrawerElement>;
            "sf-tooltip": LocalJSX.SfTooltip & JSXBase.HTMLAttributes<HTMLSfTooltipElement>;
        }
    }
}
